version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm install --save-dev firebase-tools
      - ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive
