version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g firebase-tools
      - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
