import Image from "next/image";
import { FC, useContext } from "react";
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth";
import { FIREBASE_UI_CONFIG } from "lib/firebase.config";
import { AuthContext } from "lib/context/authContext";
import { FIREBASE_AUTH } from "pages/_app";
import Navbar from "./Navbar";
import { NextPage } from "next";
import Head from "next/head";

const Page: NextPage = ({ children }) => {
  const { user } = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>Nikhil Dev Chunchu - Engineer, Musician, Doggy Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col">
        <Navbar user={user} />
        {children}
      </main>
    </>
  );
};

export default Page;
