baseURL = 'https://nikhildev.com'
languageCode = 'en-US'
title = 'Nikhil Dev Chunchu'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
