import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Intro from "./components/Intro";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nikhil Dev Chunchu - Engineer, Musician, Doggy Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>

      <main className={styles.main}>
        <Intro />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
