import type { NextPage } from "next";
import Head from "next/head";
import Intro from "../components/Intro";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nikhil Dev Chunchu - Engineer, Musician, Doggy Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />
      </main>
    </div>
  );
};

export default Home;
