import type { NextPage } from "next";
import Head from "next/head";
import Intro from "../components/Intro";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nikhil Dev Chunchu - Engineer, Musician, Doggy Daddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Intro />
      </main>
    </div>
  );
};

export default Home;
